quanlytailieu/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
app_name= 'user'
urlpatterns = [
    path('', home,name='home'),
    path('dangnhap/',login_attempt,name='dangnhap'),
    path('dangxuat/',Dangxuat,name='dangxuat'),
    path('dangki/',register_attempt,name='dangki'),
    path('chinhsuathongtin/',Editprofile.as_view(),name='csthongtin'),
    path('dshocsinh/',dshocsinh,name='danhsachhocsinh'),
    path('xoahocsinh/<str:pk>/', xoahocsinh, name='xoahocsinh'),
    path('baitap/<int:baitap_id>', detailBaitap, name='baitap'),
    path('nopbaitap/',Nopbaitap.as_view(),name='nopbaitap'),
    path('updatebaitap/<str:pk>', Updatebaitap, name='updatebaitap'),
    path('xoabaitap/<str:pk>/', Xoabaitap, name='xoabaitap'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Nguoidung(models.Model):
    ten = models.CharField(max_length=50, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sex_choice = (('Nam', 'Nam'), ('Nữ', 'Nữ'))
    gioitinh = models.CharField(max_length=10, choices=sex_choice, default='', null=True)
    ngaysinh = models.DateField(null=True)
    phone = models.CharField(max_length=15, null=True,)
    def __str__(self):
        return self.user.username

class Baitap(models.Model):
    nguoidung = models.ForeignKey(Nguoidung,on_delete=models.CASCADE,null=True)
    ten = models.CharField(max_length=50, null=True)
    mota = models.CharField(max_length=1000, null=True)
    giaovienhd =models.CharField(max_length=50, null=True)
    filebaocao = models.FileField(upload_to='')
    filezip = models.FileField(upload_to='')

    def __str__(self):
        return self.ten

templates/templates/baitaphs.html
{% extends 'templates/index.html' %}
    {% block content %}
<div class="content">
                <div class="row">
                    <div class="col-sm-7 col-6">
                        <h4 class="page-title">Thông tin cá nhân</h4>
                    </div>

                    <div class="col-sm-5 col-6 text-right m-b-30">
                        <a href="{% url 'user:csthongtin' %}" class="btn btn-primary btn-rounded"><i class="fa fa-plus"></i> Chỉnh sửa thông tin</a>
                    </div>
                </div>
                <div class="card-box profile-header">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="profile-view">
                                <div class="profile-img-wrap">
                                    <div class="profile-img">
                                        <a href="#"><img class="avatar" src="assets/img/doctor-03.jpg" alt=""></a>
                                    </div>
                                </div>
                                <div class="profile-basic">
                                    <div class="row">
                                        <div class="col-md-5">
                                            <div class="profile-info-left">
                                                <h3 class="user-name m-t-0 mb-0">{{nd.ten}}</h3>

                                            </div>
                                        </div>
                                        <div class="col-md-7">
                                            <ul class="personal-info">
                                                <li>
                                                    <span class="title">Số điện thoại:</span>
                                                    <span class="text"><a href="#">{{nd.phone}}</a></span>
                                                </li>
                                                <li>
                                                    <span class="title">Email:</span>
                                                    <span class="text"><a href="#">{{nd.user.email}}</a></span>
                                                </li>
                                                <li>
                                                    <span class="title">Ngày sinh:</span>
                                                    <span class="text">{{nd.ngaysinh}}</span>
                                                </li>

                                                <li>
                                                    <span class="title">Giới tính:</span>
                                                    <span class="text">{{nd.gioitinh}}</span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

				<div class="profile-tabs">

					<div class="tab-content">
                        {% if nd %}
						<div class="tab-pane show active" id="about-cont">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card-box">
                            <h3 class="card-title">Danh sách bài tập của {{ nd.ten }}</h3>
                            <div class="experience-box">
                                <ul class="experience-list">
                                    {% for baitap in nd.baitap_set.all %}
                                    <li>
                                        <div class="experience-user">
                                            <div class="before-circle"></div>
                                        </div>
                                        <div class="experience-content">
                                            <div class="timeline-content">
                                                <a href="#/" class="name"> Tên bài tập :{{ baitap.ten }}</a>
                                                <div>GVHD :{{ baitap.giaovienhd }}</div>
                                                <span class="time">Mô tả :{{ baitap.mota }}</span>
                                                <a href ="{{baitap.filebaocao.url}}" download><span class="time">{{ baitap.filebaocao }}</span></a>
                                                <a href ="{{baitap.filezip.url}}" download><span class="time">{{ baitap.filezip }}</span></a>

                                            </div>
                                        </div>
                                    </li>
                                    {% endfor %}

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                </div>

                 {% endif %}

						<div class="tab-pane" id="bottom-tab2">
							Tab content 2
						</div>
						<div class="tab-pane" id="bottom-tab3">
							Tab content 3
						</div>
					</div>
				</div>
            </div>
{% endblock %}

templates/templates/dangki.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- register24:03-->
<head>
    <style>


    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
		<script src="{% static 'assets/js/respond.min.js' %}"></script>
	<![endif]-->
</head>

<body>
    <div class="main-wrapper  account-wrapper">
        <div class="account-page">
            <div class="account-center">
                <div class="account-box">
                    <form action="" class="form-signin" method="post">
                        {% if messages %}

                        {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                        {% endfor %}

                    {% endif %}
                        {% csrf_token %}
						<div class="account-logo">
                            <a href="index-2.html"><img src="{% static 'assets/img/logo1.png' %}" alt=""></a>
                        </div>
                        <div class="form-group">
                            <label>Tên đăng nhập</label>
                            <input type="text" class="form-control" name="username">
                        </div>
                        <div class="form-group">
                            <label>Email </label>
                            <input type="email" class="form-control" name="email">
                        </div>
                        <div class="form-group">
                            <label>Mật khẩu</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <div class="form-group">
                            <label>Số điện thoại</label>
                            <input type="text" class="form-control" name="phone">
                        </div>
                        <div class="form-group text-center">
                            <button class="btn btn-primary account-btn" type="submit">Đăng kí</button>
                                </div>
                        <div class="text-center login-link">
                            Bạn đã có tài khoản? <a href="{% url 'user:dangnhap' %}">Đăng nhập</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>
</body>


<!-- register24:03-->

templates/templates/dshocsinh.html
{% extends 'templates/index.html' %}
    {% block content %}
 			<div class="content">
                <div class="row">
                    <div class="col-sm-4 col-3">
                        <p></p><h4 class="page-title">Danh sách học sinh</h4>
                    </div>
                    <div class="col-sm-8 col-9 text-right m-b-20">
						<form  method="get">
<!--                      <p><button type="submit" class="btn btn-primary">Search</button></p></form>-->
<!--					<a href="" class="btn btn btn-primary btn-rounded float-right"><i class="fa fa-plus"></i>Thêm học sinh</a>-->
                    </div>
                </div>
				<div class="row">
					<div class="col-md-12">
						<div class="table-responsive">
							<table class="table table-border table-striped custom-table datatable mb-0">
								<thead>
									<tr>
										<th>ID</th>
										<th>Tên</th>
										<th>Ngày sinh</th>
										<th>Số diện thoai</th>
										<th>Email</th>
										<th>Giới tính</th>
										<th>Thêm</th>
									</tr>
								</thead>
								<tbody>
									{% for i in ds %}
										<tr>
											<td>{{i.id}}</td>
											<td>{{i.ten}}</td>
											<td>{{i.ngaysinh}}</td>
											<td>{{i.phone}}</td>
											<td>{{i.user.email}}</td>
											<td>{{i.gioitinh}}</td>
											<td class="text-right">
												<div class="dropdown dropdown-action">
													<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
													<div class="dropdown-menu dropdown-menu-right">
														<a class="dropdown-item" href="{% url 'user:baitap' i.id %}"><i class="fa fa-pencil m-r-5"></i> Xem bài tập</a>
														<a class="dropdown-item" href="{% url 'user:xoahocsinh' i.id %}"><i class="fa fa-pencil m-r-5"></i> Xóa</a>
													</div>
												</div>
											</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
                </div>
            </div>
    {% endblock %}

templates/templates/home.html
{% extends 'templates/index.html' %}
    {% block content %}
<div class="content">
                        {% if messages %}

                        {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                <div class="row">
                    <div class="col-sm-7 col-6">
                        <h4 class="page-title">Thông tin cá nhân</h4>
                    </div>

                    <div class="col-sm-5 col-6 text-right m-b-30">
                        <a href="{% url 'user:csthongtin' %}" class="btn btn-primary btn-rounded"><i class="fa fa-plus"></i> Chỉnh sửa thông tin</a>
                    </div>
                </div>
                <div class="card-box profile-header">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="profile-view">
                                <div class="profile-img-wrap">
                                    <div class="profile-img">
                                        <a href="#"><img class="avatar" src="assets/img/doctor-03.jpg" alt=""></a>
                                    </div>
                                </div>
                                <div class="profile-basic">
                                    <div class="row">
                                        <div class="col-md-5">
                                            <div class="profile-info-left">
                                                <h3 class="user-name m-t-0 mb-0">{{nd.ten}}</h3>

                                            </div>
                                        </div>
                                        <div class="col-md-7">
                                            <ul class="personal-info">
                                                <li>
                                                    <span class="title">Số điện thoại:</span>
                                                    <span class="text"><a href="#">{{nd.phone}}</a></span>
                                                </li>
                                                <li>
                                                    <span class="title">Email:</span>
                                                    <span class="text"><a href="#">{{ur.email}}</a></span>
                                                </li>
                                                <li>
                                                    <span class="title">Ngày sinh:</span>
                                                    <span class="text">{{nd.ngaysinh}}</span>
                                                </li>

                                                <li>
                                                    <span class="title">Giới tính:</span>
                                                    <span class="text">{{nd.gioitinh}}</span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

				<div class="profile-tabs">

					<div class="tab-content">
                        {% if nd %}
						<div class="tab-pane show active" id="about-cont">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card-box">
                            <h3 class="card-title">Danh sách bài tập của {{ nd.ten }}</h3>
                            <div class="experience-box">
                                <ul class="experience-list">
                                    {% for baitap in nd.baitap_set.all %}
                                    <li>
                                        <div class="experience-user">
                                            <div class="before-circle"></div>
                                        </div>
                                        <div class="experience-content">
                                            <div class="timeline-content">
                                               <p> <a href="{% url 'user:xoabaitap' baitap.id %}">Xóa</a>    <a href="{% url 'user:updatebaitap' baitap.id %}">Sửa</a></p>
                                                Tên bài tập :{{ baitap.ten }}
                                                <div>GVHD :{{ baitap.giaovienhd }}</div>
                                                <span class="time">Mô tả :{{ baitap.mota }}</span>
                                                <a href ="{{baitap.filebaocao.url}}" download><span class="time">{{ baitap.filebaocao }}</span></a>
                                                <a href ="{{baitap.filezip.url}}" download><span class="time">{{ baitap.filezip }}</span></a>

                                            </div>
                                        </div>
                                    </li>
                                    {% endfor %}

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                </div>

                 {% endif %}

						<div class="tab-pane" id="bottom-tab2">
							Tab content 2
						</div>
						<div class="tab-pane" id="bottom-tab3">
							Tab content 3
						</div>
					</div>
				</div>
            </div>
{% endblock %}

templates/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- index22:59-->
<head>
    <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
		<script src="{% static 'assets/js/respond.min.js' %}"></script>
	<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <div class="header">
			<div class="header-left">
				<a href="{% url 'user:home' %}" class="logo">
					<img src="{% static 'assets/img/logo1.png' %}" width="70" height="70" alt=""> </i> <span><h4>Quản lý bài tập</h4></span>
				</a>
			</div>

            <a id="mobile_btn" class="mobile_btn float-left" href="#sidebar"><i class="fa fa-bars"></i></a>
            <ul class="nav user-menu float-right">
                <li class="nav-item dropdown d-none d-sm-block">
                    <div class="dropdown-menu notifications">
                        <div class="topnav-dropdown-header">
                            <span>Notifications</span>
                        </div>
                        <div class="drop-scroll">
                            <ul class="notification-list">
                                <li class="notification-message">
                                    <a href="activities.html">
                                        <div class="media">
											<span class="avatar">
												<img alt="John Doe" src="{% static 'assets/img/user.jpg' %}" class="img-fluid">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">John Doe</span> added new task <span class="noti-title">Patient appointment booking</span></p>
												<p class="noti-time"><span class="notification-time">4 mins ago</span></p>
											</div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="topnav-dropdown-footer">
                            <a href="activities.html">View all Notifications</a>
                        </div>
                    </div>
                </li>
                <li class="nav-item dropdown d-none d-sm-block">

                </li>
                <li class="nav-item dropdown has-arrow">
                    <a href="#" class="dropdown-toggle nav-link user-link" data-toggle="dropdown">
                        <span class="user-img">
							<img class="rounded-circle" src="{% static 'assets/img/user.jpg' %}" width="24" alt="Admin">
							<span class="status online"></span>
						</span>
						<span>{{request.user}}</span>
                    </a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="">Settings</a>
						<a class="dropdown-item" href="{% url 'user:dangxuat' %}">Logout</a>
					</div>
                </li>
            </ul>
        </div>
        <div class="sidebar" id="sidebar">
            <div class="sidebar-inner slimscroll">
                <div id="sidebar-menu" class="sidebar-menu">
                    <ul>
                       <li class="menu-title">Chính</li>
						<li>

                            <a href="{% url 'user:nopbaitap' %}"><i class="fa fa-book" aria-hidden="true"></i> <span>Nộp bài tập</span></a>
                        </li>
                        <li>
							<a href="{% url 'user:danhsachhocsinh' %}"><i class="fa fa-user"aria-hidden="true"></i> <span>Danh sách học sinh </span> </a>

						</li>

                        <li>
                            <a href=""><i class="fa fa-cog"></i> <span>Thiết lập</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="page-wrapper">
            <div class="content">
                {% block content %}

                {% endblock %}
            </div>
            <div class="notification-box">
                <div class="msg-sidebar notifications msg-noti">
                    <div class="topnav-dropdown-header">
                        <span>Messages</span>
                    </div>
                    </div>
                    <div class="topnav-dropdown-footer">
                        <a href=" ">See all messages</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar-overlay" data-reff=""></div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'assets/js/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/js/chart.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>

</body>


<!-- index22:59-->
</html>

templates/templates/login.html
{% load static %}
<!DOCTYPE html>

<html lang="en">


<!-- login23:11-->
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <title>Preclinic - Medical & Hospital - Bootstrap 4 Admin Template</title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
		<script src="{% static 'assets/js/respond.min.js' %}"></script>
	<![endif]-->
</head>

<body>
    <div class="main-wrapper account-wrapper">
        <div class="account-page">
			<div class="account-center">
				<div class="account-box">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% if messages %}

                        {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                        {% endfor %}

                    {% endif %}
					{% csrf_token %}
						<div class="account-logo">
                            <a href="index-2.html"><img src="{% static 'assets/img/logo1.png' %}" alt=""></a>
                        </div>
                        <div class="form-group">
                            <label>Tên đăng nhập</label>
                            <input type="text" autofocus="" class="form-control" name="username">
                        </div>
                        <div class="form-group">
                            <label>Mật khẩu</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <div class="form-group text-right">
                            <a href="forgot-password.html">Bạn quên mật khẩu?</a>
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-primary account-btn">Đăng nhập</button>
                        </div>
                        <div class="text-center register-link">
                            Bạn chưa có tài khoản <a href="{% url 'user:dangki' %}">Đăng kí ngay</a>
                        </div>
                    </form>
                </div>
			</div>
        </div>
    </div>
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>
</body>


<!-- login23:12-->
</html>

templates/templates/nopbai.html
{% extends 'templates/index.html' %}
    {% block content %}
    {% load static %}

  <body>
<div class="container mt-5">
    <form  action="" method="POST" enctype="multipart/form-data">

        <div class="form-group">
           <label for="{{form.file_name.id_for_label}}">Tên bài tập</label>
          {{form.ten}}
        </div>
        <div class="form-group">
          <label for="{{form.file_name.id_for_label}}">Mô tả</label>
          {{form.mota}}
        </div>
        <div class="form-group">
          <label for="{{form.file_name.id_for_label}}">Giáo viên hướng dẫn</label>
          {{form.giaovienhd}}
        </div>
        <div class="form-group">
            <label for="{{form.files_data.id_for_label}}">File 1</label>
            {{form.filebaocao}}
          </div>
        <div class="form-group">
            <label for="{{form.files_data.id_for_label}}">File 2</label>
            {{form.filezip}}
          </div>
          {% csrf_token %}


        <button type="submit" class="btn btn-primary">Nộp</button>
      </form>

</div>



  ` <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>
  </body>
{% endblock %}

templates/templates/xoabaitap.html
{% extends 'templates/index.html' %}
    {% block content %}
    <div class="content">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Xóa học sinh</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <p>Bạn có muốn xóa baitap "{{baitap.ten}}" này ?</p>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="m-t-20 text-center">
                        <a href="{% url 'user:danhsachhocsinh' %} "><button type="button" class="btn btn-outline-secondary">Hủy</button></a>
                        <button type="submit" class="btn btn-outline-primary">Xóa</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

templates/templates/xoahocsinh.html
{% extends 'templates/index.html' %}
    {% block content %}
    <div class="content">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Xóa học sinh</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <p>Bạn có muốn xóa hocsinh "{{hocsinh.ten}}" này ?</p>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="m-t-20 text-center">
                        <a href="{% url 'user:danhsachhocsinh' %} "><button type="button" class="btn btn-outline-secondary">Hủy</button></a>
                        <button type="submit" class="btn btn-outline-primary">Xóa</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}